- ros_topic_name: "/fr/hip_roll_angle"
  ign_topic_name: "/fr/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/fr/hip_pitch_angle"
  ign_topic_name: "/fr/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/fr/knee_pitch_angle"
  ign_topic_name: "/fr/knee_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/bl/hip_roll_angle"
  ign_topic_name: "/bl/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/bl/hip_pitch_angle"
  ign_topic_name: "/bl/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/bl/knee_pitch_angle"
  ign_topic_name: "/bl/knee_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/fl/hip_roll_angle"
  ign_topic_name: "/fl/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/fl/hip_pitch_angle"
  ign_topic_name: "/fl/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/fl/knee_pitch_angle"
  ign_topic_name: "/fl/knee_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/br/hip_roll_angle"
  ign_topic_name: "/br/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/br/hip_pitch_angle"
  ign_topic_name: "/br/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/br/knee_pitch_angle"
  ign_topic_name: "/br/knee_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"
