- ros_topic_name: "/chitrak/front_right_hip_roll_angle"
  ign_topic_name: "/fr/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/front_right_hip_pitch_angle"
  ign_topic_name: "/fr/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/front_right_knee_angle"
  ign_topic_name: "/fr/knee_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/back_left_hip_roll_angle"
  ign_topic_name: "/bl/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/back_left_hip_pitch_angle"
  ign_topic_name: "/bl/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/back_left_knee_angle"
  ign_topic_name: "/bl/knee_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/front_left_hip_roll_angle"
  ign_topic_name: "/fl/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/front_left_hip_pitch_angle"
  ign_topic_name: "/fl/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/front_left_knee_angle"
  ign_topic_name: "/fl/knee_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/back_right_hip_roll_angle"
  ign_topic_name: "/br/hip_roll_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/back_right_hip_pitch_angle"
  ign_topic_name: "/br/hip_pitch_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/chitrak/back_right_knee_angle"
  ign_topic_name: "/br/knee_angle"
  ros_type_name: "std_msgs/msg/Float64"
  ign_type_name: "ignition.msgs.Double"
  direction: "BIDIRECTIONAL"

- ros_topic_name: "/joint_states"
  ign_topic_name: "/chitrak/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  ign_type_name: "ignition.msgs.Model"
  direction: "IGN_TO_ROS"
